[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "nsisunbz2"
version = "1.0.7"
readme = "README.md"

[project.scripts]
nsisunbz2 = "nsisunbz2.cli:main"
